version: "3"
services:
 vampi-vulnerable:
  image: vampi_docker:latest
  container_name: vampi-vulnerable
  ports:
   - 8000:5000
  environment:
   - vulnerable=1
   - tokentimetolive=36600
  volumes:
   - ./api_views:/vampi/api_views
   - ./models:/vampi/models 

